{% set name = "cosmix" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cosmix-{{ version }}.tar.gz
  sha256: 1c079d67281d3fcb4605b71a0cbba33e26a271a8b9ffde670755a5c5995f31c4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3
    - wheel >=0.29.0
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy
    - tqdm

test:
  imports:
    - cosmix
    - cosmix.landau
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/cosmix/
  summary: Cosmic ray model for astronomical imaging detectors
  dev_url: https://gitlab.com/david.lucsanyi/cosmix
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flemmel
